name: Release

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Release
        run: npx github-release-notes release --token=${{ secrets.GITHUB_TOKEN }} -d -D commits
